### GET hello
GET http://localhost:8080/hello


### GET getBusinessPartners
GET http://localhost:8080/businessPartners

### GET getBusinessPartner
GET http://localhost:8080/businessPartners/1003767


### PUT updateBusinessPartner
PUT http://localhost:8080/businessPartners/1003767
Content-Type: application/json

{
  "FirstName": "Kyle",
  "IsFemale": true,
  "IsMale": false,
  "LastName": "Coe"
}
